/**
 * Comprehensive Presets Library for Standard Cybersecurity, Assurance, and Privacy Frameworks.
 * Used for pre-filling "Add Framework" templates, seeding databases, and populating baseline audit controls.
 */

export interface PresetControl {
  id: string;
  title: string;
  domain: string;
  description: string;
  mappedFrameworks?: string[];
}

export interface FrameworkPreset {
  id: string;
  name: string;
  shortName: string;
  version: string;
  category: "Information Security" | "Cybersecurity" | "Risk Management" | "Compliance" | "Assurance" | "Privacy";
  description: string;
  controls: PresetControl[];
}

export const FRAMEWORK_PRESETS: FrameworkPreset[] = [
  {
    id: "pci-dss",
    name: "PCI DSS v4.0 - Payment Card Industry Data Security Standard",
    shortName: "PCI DSS",
    version: "4.0",
    category: "Compliance",
    description: "Global security standard required for organizations storing, processing, or transmitting cardholder data (CHD) and sensitive authentication data (SAD).",
    controls: [
      {
        id: "PCI-1.1",
        title: "Network Security Controls & Firewalls",
        domain: "Build and Maintain a Secure Network",
        description: "Network security controls are configured and maintained to protect cardholder data environment (CDE) perimeters.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "NIST CSF"],
      },
      {
        id: "PCI-2.2",
        title: "System Configuration Hardening",
        domain: "Build and Maintain a Secure Network",
        description: "System components are configured and managed in accordance with documented, industry-accepted system hardening standards.",
        mappedFrameworks: ["ISO 27001", "CIS Controls", "NIST 800-53"],
      },
      {
        id: "PCI-3.4",
        title: "Cardholder Data Encryption at Rest",
        domain: "Protect Cardholder Data",
        description: "Primary Account Numbers (PAN) and sensitive authentication data are rendered unreadable anywhere they are stored using strong cryptographic algorithms.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "NIST CSF"],
      },
      {
        id: "PCI-4.2",
        title: "Encryption in Transit Across Open Public Networks",
        domain: "Protect Cardholder Data",
        description: "PAN is encrypted during transmission over open, public networks using TLS 1.2/1.3 with validated ciphers.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "PCI-5.2",
        title: "Malware Prevention & Active Signatures",
        domain: "Maintain a Vulnerability Management Program",
        description: "Anti-malware solutions are deployed on all system components commonly affected by malware and kept up to date.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
      {
        id: "PCI-6.4",
        title: "Web Application Firewalls & Secure Coding",
        domain: "Maintain a Vulnerability Management Program",
        description: "Public-facing web applications are protected against automated attacks via automated technical solutions (WAF) or code reviews.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "PCI-7.2",
        title: "Need-to-Know Access Controls",
        domain: "Implement Strong Access Control Measures",
        description: "Access to system components and data is strictly limited to individuals whose job requires such access based on least privilege.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "NIST CSF"],
      },
      {
        id: "PCI-8.3",
        title: "Multi-Factor Authentication (MFA) for CDE",
        domain: "Implement Strong Access Control Measures",
        description: "Multi-factor authentication (MFA) is strictly enforced for all administrative and non-console access to the cardholder environment.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "NIST 800-53"],
      },
      {
        id: "PCI-10.2",
        title: "Audit Logging of Cardholder Access & Privilege Escalation",
        domain: "Regularly Monitor and Test Networks",
        description: "Audit trails are enabled and automatically record all user access to cardholder data, administrative actions, and invalid access attempts.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "PCI-11.3",
        title: "Quarterly Vulnerability Scanning & Annual Penetration Testing",
        domain: "Regularly Monitor and Test Networks",
        description: "External vulnerability scans are performed quarterly by an ASV, internal scans quarterly, and annual penetration testing executed.",
        mappedFrameworks: ["SOC 2", "NIST CSF"],
      },
    ],
  },
  {
    id: "hipaa",
    name: "HIPAA Security & Privacy Rule (45 CFR Part 160/164)",
    shortName: "HIPAA",
    version: "2013 Final Omnibus",
    category: "Privacy",
    description: "United States national statutory standard for protecting electronic Protected Health Information (ePHI) across Covered Entities and Business Associates.",
    controls: [
      {
        id: "HIPAA-164.308.a.1",
        title: "Security Management Process & Risk Analysis",
        domain: "Administrative Safeguards",
        description: "Implement policies and procedures to prevent, detect, contain, and correct security violations; conduct regular accurate ePHI risk assessments.",
        mappedFrameworks: ["ISO 27001", "NIST CSF", "SOC 2"],
      },
      {
        id: "HIPAA-164.308.a.3",
        title: "Workforce Security & Authorization Clearance",
        domain: "Administrative Safeguards",
        description: "Implement procedures to ensure that all members of workforce have appropriate access to electronic protected health information.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "HIPAA-164.308.a.5",
        title: "Security Awareness and Training",
        domain: "Administrative Safeguards",
        description: "Implement a security awareness and training program for all members of its workforce, including periodic reminders and password hygiene.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
      {
        id: "HIPAA-164.308.b.1",
        title: "Business Associate Agreements (BAA)",
        domain: "Administrative Safeguards",
        description: "Execute binding Business Associate Agreements ensuring vendors and subcontractors implement equivalent statutory safeguards for ePHI.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "HIPAA-164.310.a.1",
        title: "Facility Access Controls & Physical Validation",
        domain: "Physical Safeguards",
        description: "Implement policies and procedures to limit physical access to electronic information systems and the facilities in which they are housed.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "HIPAA-164.310.d.1",
        title: "Device and Media Controls (Sanitization & Disposal)",
        domain: "Physical Safeguards",
        description: "Implement policies and procedures that govern the receipt, removal, hardware sanitization, and cryptographic disposal of ePHI media.",
        mappedFrameworks: ["ISO 27001", "NIST 800-53"],
      },
      {
        id: "HIPAA-164.312.a.1",
        title: "Unique User Identification & Emergency Access",
        domain: "Technical Safeguards",
        description: "Assign a unique name and/or number for identifying and tracking user identity, and establish emergency 'break-glass' access procedures.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "HIPAA-164.312.a.2",
        title: "Automatic Logoff & Workstation Session Lock",
        domain: "Technical Safeguards",
        description: "Implement electronic procedures that terminate an active electronic session after a predetermined time of inactivity.",
        mappedFrameworks: ["ISO 27001", "NIST 800-53"],
      },
      {
        id: "HIPAA-164.312.b",
        title: "Audit Controls and Activity Tracking",
        domain: "Technical Safeguards",
        description: "Implement hardware, software, and procedural mechanisms that record and examine activity in information systems containing or using ePHI.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "HIPAA-164.312.e.1",
        title: "Transmission Security & TLS End-to-End Encryption",
        domain: "Technical Safeguards",
        description: "Implement technical security measures to guard against unauthorized access to ePHI that is being transmitted over an electronic communications network.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "NIST CSF"],
      },
    ],
  },
  {
    id: "gdpr",
    name: "GDPR - General Data Protection Regulation (EU 2016/679)",
    shortName: "GDPR",
    version: "Regulation (EU) 2016/679",
    category: "Privacy",
    description: "European Union regulation on data protection and privacy for all individuals within the EU and the European Economic Area (EEA), addressing data transfer outside the EEA.",
    controls: [
      {
        id: "GDPR-Art.5",
        title: "Principles Relating to Processing of Personal Data",
        domain: "Data Protection Principles",
        description: "Personal data shall be processed lawfully, fairly, transparently, with purpose limitation, data minimization, accuracy, and storage limitation.",
        mappedFrameworks: ["ISO 27701", "SOC 2"],
      },
      {
        id: "GDPR-Art.6",
        title: "Lawfulness of Processing & Legal Basis",
        domain: "Lawful Basis",
        description: "Maintain verified, documented legal basis for processing operations: explicit consent, contractual necessity, legal obligation, or legitimate interest.",
        mappedFrameworks: ["ISO 27701"],
      },
      {
        id: "GDPR-Art.15-20",
        title: "Data Subject Access & Portability Requests (DSAR)",
        domain: "Data Subject Rights",
        description: "Operational workflows to fulfill data subject rights: right of access, rectification, erasure ('right to be forgotten'), restriction, and portability within 30 days.",
        mappedFrameworks: ["ISO 27701"],
      },
      {
        id: "GDPR-Art.25",
        title: "Data Protection by Design and by Default",
        domain: "Controller Obligations",
        description: "Implement appropriate technical and organizational measures (e.g. pseudonymization) designed to implement data-protection principles effectively.",
        mappedFrameworks: ["ISO 27001", "ISO 27701"],
      },
      {
        id: "GDPR-Art.30",
        title: "Records of Processing Activities (ROPA)",
        domain: "Controller & Processor Obligations",
        description: "Maintain a comprehensive written register of all categories of processing activities carried out as a controller or processor.",
        mappedFrameworks: ["ISO 27701"],
      },
      {
        id: "GDPR-Art.32",
        title: "Security of Processing & Pseudonymisation",
        domain: "Technical & Organizational Security",
        description: "Implement appropriate technical measures including pseudonymization, end-to-end encryption, confidentiality, and regular effectiveness testing.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "NIST CSF"],
      },
      {
        id: "GDPR-Art.33-34",
        title: "72-Hour Personal Data Breach Notification",
        domain: "Incident Management",
        description: "Notify supervisory authority of personal data breach within 72 hours of becoming aware, and notify affected data subjects without undue delay when high risk.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "NIST CSF"],
      },
      {
        id: "GDPR-Art.35",
        title: "Data Protection Impact Assessments (DPIA)",
        domain: "Risk Management",
        description: "Conduct formal Data Protection Impact Assessments prior to processing likely to result in a high risk to the rights and freedoms of natural persons.",
        mappedFrameworks: ["ISO 27001", "ISO 27701"],
      },
      {
        id: "GDPR-Art.44-49",
        title: "Cross-Border International Data Transfers (SCCs)",
        domain: "International Transfers",
        description: "Ensure transfers of personal data to third countries outside the EEA rely on adequacy decisions, Standard Contractual Clauses (SCCs), or approved BCRs.",
        mappedFrameworks: ["ISO 27701"],
      },
    ],
  },
  {
    id: "cis-v8",
    name: "CIS Critical Security Controls v8",
    shortName: "CIS Controls",
    version: "v8",
    category: "Cybersecurity",
    description: "Prescriptive, prioritized set of 18 cybersecurity best practices published by the Center for Internet Security (CIS) mapped into Implementation Groups IG1, IG2, IG3.",
    controls: [
      {
        id: "CIS-1",
        title: "Inventory and Control of Enterprise Assets",
        domain: "Asset Security",
        description: "Actively manage (inventory, track, and correct) all enterprise assets connected to the infrastructure physically, virtually, or remotely.",
        mappedFrameworks: ["ISO 27001", "NIST CSF", "NIST 800-53"],
      },
      {
        id: "CIS-2",
        title: "Inventory and Control of Software Assets",
        domain: "Software Management",
        description: "Actively manage all software on the network so that only authorized software is installed and can execute.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
      {
        id: "CIS-3",
        title: "Data Protection (Classification & Handling)",
        domain: "Data Protection",
        description: "Develop processes and technical controls to identify, classify, securely handle, retain, and dispose of data.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "GDPR"],
      },
      {
        id: "CIS-4",
        title: "Secure Configuration of Enterprise Assets and Software",
        domain: "Configuration Management",
        description: "Establish and maintain the secure configuration of enterprise assets and software using strict benchmarks.",
        mappedFrameworks: ["ISO 27001", "NIST 800-53"],
      },
      {
        id: "CIS-5",
        title: "Account Management (Lifecycle & Deprovisioning)",
        domain: "Identity & Access Management",
        description: "Use processes and tools to assign and manage authorization to credentials for user accounts, including administrator accounts.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "CIS-6",
        title: "Access Control Management (MFA & Least Privilege)",
        domain: "Access Control",
        description: "Use processes and tools to create, assign, manage, and revoke access credentials and privileges for user, administrator, and service accounts.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "PCI DSS"],
      },
      {
        id: "CIS-7",
        title: "Continuous Vulnerability Management",
        domain: "Vulnerability Management",
        description: "Develop a plan to continuously assess and track vulnerabilities on all enterprise assets within the infrastructure.",
        mappedFrameworks: ["ISO 27001", "NIST CSF", "SOC 2"],
      },
      {
        id: "CIS-8",
        title: "Audit Log Management (Collection & Protection)",
        domain: "Audit & Logging",
        description: "Collect, alert, review, and retain audit logs of events that could help detect, understand, or recover from an attack.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "NIST 800-53"],
      },
      {
        id: "CIS-10",
        title: "Malware Defenses",
        domain: "Malware Protection",
        description: "Prevent or control the installation, spread, and execution of malicious applications, code, or scripts on enterprise assets.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
      {
        id: "CIS-17",
        title: "Incident Response Management",
        domain: "Incident Response",
        description: "Establish a program to develop and maintain an incident response capability to prepare, detect, and quickly respond to an attack.",
        mappedFrameworks: ["ISO 27001", "NIST CSF", "SOC 2"],
      },
    ],
  },
  {
    id: "nist-800-53",
    name: "NIST SP 800-53 Rev. 5 - Security and Privacy Controls",
    shortName: "NIST 800-53",
    version: "Rev. 5",
    category: "Information Security",
    description: "Catalog of security and privacy controls for federal information systems and organizations protecting state, defense, and high-assurance commercial infrastructure.",
    controls: [
      {
        id: "AC-2",
        title: "Account Management",
        domain: "Access Control (AC)",
        description: "Manage system accounts: establish, activate, modify, review, disable, and remove accounts in accordance with organizational procedures.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "CIS Controls"],
      },
      {
        id: "AC-3",
        title: "Access Enforcement",
        domain: "Access Control (AC)",
        description: "Enforce approved authorizations for logical access to information and system resources in accordance with applicable access control policies.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "AU-2",
        title: "Event Logging Scope & Audit Generation",
        domain: "Audit and Accountability (AU)",
        description: "Identify auditable events and generate audit records containing information to establish what occurred, when, and by whom.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "PCI DSS"],
      },
      {
        id: "AU-6",
        title: "Audit Record Review, Analysis, and Reporting",
        domain: "Audit and Accountability (AU)",
        description: "Review and analyze system audit records for indications of unusual or suspicious activity and report findings.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
      {
        id: "CM-2",
        title: "Baseline Configuration Management",
        domain: "Configuration Management (CM)",
        description: "Develop, document, and maintain under configuration control, a current baseline configuration of the information system.",
        mappedFrameworks: ["ISO 27001", "CIS Controls"],
      },
      {
        id: "IA-2",
        title: "Identification and Authentication (Organizational Users)",
        domain: "Identification and Authentication (IA)",
        description: "Uniquely identify and authenticate organizational users (or processes acting on behalf of users) using multi-factor authenticators.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "PCI DSS"],
      },
      {
        id: "IR-4",
        title: "Incident Handling & Containment",
        domain: "Incident Response (IR)",
        description: "Implement an incident handling capability for incidents that includes preparation, detection and analysis, containment, eradication, and recovery.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
      {
        id: "RA-5",
        title: "Vulnerability Monitoring and Scanning",
        domain: "Risk Assessment (RA)",
        description: "Monitor for vulnerabilities in the system and hosted applications; remediate legitimate vulnerabilities in accordance with risk assessments.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "PCI DSS"],
      },
      {
        id: "SC-8",
        title: "Transmission Confidentiality and Integrity",
        domain: "System and Communications Protection (SC)",
        description: "Protect the confidentiality and integrity of transmitted information using cryptography across internal and external networks.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "SI-4",
        title: "Information System Monitoring",
        domain: "System and Information Integrity (SI)",
        description: "Monitor the system to detect attacks, indicators of potential compromise, and unauthorized local, network, and remote connections.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
    ],
  },
  {
    id: "iso-27701",
    name: "ISO/IEC 27701:2019 - Privacy Information Management System",
    shortName: "ISO 27701",
    version: "2019",
    category: "Privacy",
    description: "International standard providing guidance for establishing, implementing, maintaining and continually improving a Privacy Information Management System (PIMS) as an extension to ISO 27001.",
    controls: [
      {
        id: "PIMS-6.2",
        title: "PIMS Context & Stakeholder Privacy Requirements",
        domain: "PIMS Governance",
        description: "Determine external and internal factors, relevant interested parties, and legal/regulatory requirements regarding Personally Identifiable Information (PII).",
        mappedFrameworks: ["ISO 27001", "GDPR"],
      },
      {
        id: "PIMS-7.2.1",
        title: "Identify Privacy Basis & Objectives",
        domain: "PII Controller Controls",
        description: "Document and maintain the specified, explicit, and legitimate purposes for processing PII in accordance with applicable laws.",
        mappedFrameworks: ["GDPR"],
      },
      {
        id: "PIMS-7.2.4",
        title: "Obtain and Record Privacy Consent",
        domain: "PII Controller Controls",
        description: "Demonstrate that valid consent has been obtained from PII principals where consent is the basis for processing.",
        mappedFrameworks: ["GDPR"],
      },
      {
        id: "PIMS-7.3.2",
        title: "Mechanism for Fulfilling Data Subject Rights",
        domain: "PII Controller Controls",
        description: "Provide the means for PII principals to access, correct, erase, or object to the processing of their PII.",
        mappedFrameworks: ["GDPR"],
      },
      {
        id: "PIMS-7.4.1",
        title: "Privacy by Design and Default Implementation",
        domain: "PII Controller Controls",
        description: "Ensure that privacy principles and security controls are built into systems and software from the earliest stages of architectural design.",
        mappedFrameworks: ["GDPR", "ISO 27001"],
      },
      {
        id: "PIMS-8.2.1",
        title: "Customer Agreement Obligations for PII Processors",
        domain: "PII Processor Controls",
        description: "Process PII strictly in accordance with documented instructions from the PII controller under a legally binding contract.",
        mappedFrameworks: ["GDPR"],
      },
      {
        id: "PIMS-8.4.2",
        title: "Sub-Processor Authorization and Due Diligence",
        domain: "PII Processor Controls",
        description: "Engage sub-processors only with prior specific or general written authorization of the PII controller and maintain strict oversight.",
        mappedFrameworks: ["ISO 27001", "GDPR", "SOC 2"],
      },
      {
        id: "PIMS-8.5.8",
        title: "Disposal of Temporary and Cached PII Files",
        domain: "PII Processor Controls",
        description: "Ensure temporary and cached files containing PII are securely destroyed or overwritten in accordance with retention schedules.",
        mappedFrameworks: ["ISO 27001"],
      },
    ],
  },
  {
    id: "dora",
    name: "DORA - Digital Operational Resilience Act (EU 2022/2554)",
    shortName: "DORA",
    version: "Regulation (EU) 2022/2554",
    category: "Compliance",
    description: "European Union regulation establishing uniform requirements for the digital operational resilience of financial entities and critical ICT third-party service providers.",
    controls: [
      {
        id: "DORA-Art.6",
        title: "ICT Risk Management Framework Governance",
        domain: "ICT Risk Management",
        description: "Management body defines, approves, and oversees the implementation of all arrangements related to the ICT risk management framework.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
      {
        id: "DORA-Art.9",
        title: "Protection and Prevention Security Architectures",
        domain: "ICT Systems & Tools",
        description: "Deploy robust security tooling, network segmentation, authentication protocols, and patch management to minimize the impact of ICT risks.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "NIST 800-53"],
      },
      {
        id: "DORA-Art.11",
        title: "ICT Business Continuity & Disaster Recovery Plans",
        domain: "Business Continuity",
        description: "Put in place dedicated and comprehensive ICT business continuity plans, disaster recovery policies, and annual testing exercises.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "DORA-Art.17",
        title: "Major ICT-Related Incident Reporting",
        domain: "Incident Management",
        description: "Classify and report major ICT-related incidents to relevant competent authorities within initial (4h/24h), intermediate, and final deadlines.",
        mappedFrameworks: ["ISO 27001", "NIST CSF", "GDPR"],
      },
      {
        id: "DORA-Art.24",
        title: "Digital Operational Resilience Testing",
        domain: "Resilience Testing",
        description: "Establish and maintain a digital operational resilience testing program including vulnerability assessments, open source analyses, and network scans.",
        mappedFrameworks: ["SOC 2", "PCI DSS"],
      },
      {
        id: "DORA-Art.26",
        title: "Advanced Threat-Led Penetration Testing (TLPT)",
        domain: "Resilience Testing",
        description: "Perform advanced Threat-Led Penetration Testing (TLPT / TIBER-EU) at least every 3 years covering critical live production environments.",
        mappedFrameworks: ["PCI DSS"],
      },
      {
        id: "DORA-Art.28",
        title: "ICT Third-Party Risk Management & Register of Information",
        domain: "Third-Party Risk",
        description: "Maintain an exhaustive register of information regarding all contractual arrangements on the use of ICT services provided by third-party providers.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
    ],
  },
  {
    id: "csa-ccm",
    name: "CSA CCM v4 - Cloud Security Alliance Cloud Controls Matrix",
    shortName: "CSA CCM",
    version: "v4.0",
    category: "Cybersecurity",
    description: "Cybersecurity control framework designed specifically for cloud computing, acting as the de-facto baseline for the CSA STAR certification program.",
    controls: [
      {
        id: "CCM-AIS-01",
        title: "Application Security Baseline Requirements",
        domain: "Application & Interface Security",
        description: "Applications developed for cloud deployments adhere to industry security standards and undergo static and dynamic vulnerability analysis.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "CCM-BCR-02",
        title: "Cloud Disaster Recovery & Cross-Region Redundancy",
        domain: "Business Continuity & Resilience",
        description: "Business continuity and disaster recovery strategies incorporate multi-availability zone and cross-region failover automation.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "CCM-EKM-01",
        title: "Encryption Key Management Lifecycle (KMS)",
        domain: "Cryptography & Key Management",
        description: "Maintain centralized key management systems (KMS) ensuring keys are generated, rotated, stored, and revoked using FIPS 140-2/3 validated HSMs.",
        mappedFrameworks: ["ISO 27001", "PCI DSS", "NIST 800-53"],
      },
      {
        id: "CCM-IAM-03",
        title: "Privileged Identity and Service Account Governance",
        domain: "Identity & Access Management",
        description: "Enforce just-in-time (JIT) access, strict session limits, and mandatory MFA for cloud control plane and tenant administration accounts.",
        mappedFrameworks: ["ISO 27001", "SOC 2", "NIST CSF"],
      },
      {
        id: "CCM-IVS-04",
        title: "Micro-Segmentation and Virtual Network Isolation",
        domain: "Infrastructure & Virtualization Security",
        description: "Cloud tenant VPCs, Kubernetes clusters, and microservices are isolated using strict software-defined network policies and security groups.",
        mappedFrameworks: ["ISO 27001", "PCI DSS"],
      },
      {
        id: "CCM-TVM-01",
        title: "Container & Image Vulnerability Scanning",
        domain: "Threat & Vulnerability Management",
        description: "Automate container image, serverless function, and cloud VM vulnerability scanning prior to deployment in production registries.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
    ],
  },
  {
    id: "fedramp",
    name: "FedRAMP Moderate Baseline (Rev. 5 Tailored)",
    shortName: "FedRAMP",
    version: "Rev. 5 Moderate",
    category: "Government & Defense" as any,
    description: "United States Federal Risk and Authorization Management Program standardizing security authorization for cloud services used by federal agencies.",
    controls: [
      {
        id: "FED-AC-2",
        title: "Automated Account Management & 90-Day Inactive Revocation",
        domain: "Access Control",
        description: "Automatically disable accounts after 90 days of inactivity and audit privileged accounts monthly.",
        mappedFrameworks: ["NIST 800-53", "ISO 27001"],
      },
      {
        id: "FED-IA-2.1",
        title: "FIPS 140 Cryptographic Hardware Multi-Factor Authentication",
        domain: "Identification & Authentication",
        description: "Enforce hardware-backed FIDO2 / PIV / CAC multi-factor authentication for all federal cloud administrative access.",
        mappedFrameworks: ["NIST 800-53"],
      },
      {
        id: "FED-SC-13",
        title: "FIPS 140 Validated Cryptography",
        domain: "System & Communications Protection",
        description: "All data encrypted at rest and in transit must utilize NIST cryptographic module validation program (CMVP) FIPS 140-2/3 validated modules.",
        mappedFrameworks: ["NIST 800-53", "PCI DSS"],
      },
      {
        id: "FED-SI-4",
        title: "Continuous Automated Monitoring (ConMon)",
        domain: "System Integrity",
        description: "Submit monthly Continuous Monitoring (ConMon) deliverables including Plan of Action and Milestones (POA&M) and vulnerability scans to 3PAO.",
        mappedFrameworks: ["NIST 800-53", "NIST RMF"],
      },
    ],
  },
  {
    id: "soc-1",
    name: "SOC 1 / SSAE 18 (ISAE 3402) - Internal Controls over Financial Reporting",
    shortName: "SOC 1",
    version: "SSAE 18 Type II",
    category: "Assurance",
    description: "AICPA attestation standard reporting on internal controls at a service organization relevant to user entities' internal control over financial reporting (ICFR).",
    controls: [
      {
        id: "SOC1-ITGC-01",
        title: "Logical Security & Transaction Authorization Boundaries",
        domain: "IT General Controls (ITGC)",
        description: "Access to financial processing systems and data structures is restricted to authorized personnel in accordance with segregation of duties.",
        mappedFrameworks: ["SOC 2", "ISO 27001"],
      },
      {
        id: "SOC1-ITGC-02",
        title: "Program Change Management & Production Deployment Verification",
        domain: "IT General Controls (ITGC)",
        description: "Application updates impacting financial ledger calculations or data feeds undergo formal peer review, automated testing, and management sign-off.",
        mappedFrameworks: ["SOC 2", "ISO 27001"],
      },
      {
        id: "SOC1-ITGC-03",
        title: "Computer Operations, Batch Jobs & Data Backup Reconciliation",
        domain: "IT General Controls (ITGC)",
        description: "Scheduled batch processing jobs are monitored for job aborts or anomalies, and financial transaction databases backed up with verified restoral.",
        mappedFrameworks: ["SOC 2"],
      },
      {
        id: "SOC1-BC-01",
        title: "Business Process Controls: Transaction Completeness & Accuracy",
        domain: "Business Process Controls",
        description: "Reconcile input transactions against batch processing outputs to ensure zero financial record duplication, omission, or unauthorized alteration.",
        mappedFrameworks: ["SOC 2"],
      },
    ],
  },
  {
    id: "soc-2",
    name: "SOC 2 Type II - AICPA Trust Services Criteria",
    shortName: "SOC 2",
    version: "2023",
    category: "Assurance",
    description: "AICPA standard evaluating service organization controls relevant to Security, Availability, Processing Integrity, Confidentiality, and Privacy.",
    controls: [
      {
        id: "CC6.1",
        title: "Logical and Physical Access Security",
        domain: "Common Criteria / Access Control",
        description: "Logical access controls over infrastructure, applications, and architecture are restricted to authorized users via role-based access control.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
      {
        id: "CC6.6",
        title: "Perimeter Defense & Boundary Protection",
        domain: "Common Criteria / Access Control",
        description: "Logical boundaries and firewalls are maintained to protect internal environments against unauthorized external intrusion.",
        mappedFrameworks: ["ISO 27001", "PCI DSS"],
      },
      {
        id: "CC6.7",
        title: "Transmission Encryption and Key Distribution",
        domain: "Common Criteria / Access Control",
        description: "Data transmitted across public networks or between cloud tenants is encrypted using verified TLS protocols.",
        mappedFrameworks: ["ISO 27001", "PCI DSS", "NIST 800-53"],
      },
      {
        id: "CC7.2",
        title: "Anomaly Detection and Monitoring of Security Events",
        domain: "Common Criteria / System Operations",
        description: "Infrastructure is monitored continuously to identify potential vulnerabilities, unauthorized access attempts, and operational anomalies.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
      {
        id: "CC7.3",
        title: "Security Incident Response and Remediation",
        domain: "Common Criteria / Incident Response",
        description: "Security incidents are logged, escalated, investigated, and remediated in accordance with defined incident response procedures.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
      {
        id: "CC8.1",
        title: "Authorized Change Management and CI/CD Quality Gates",
        domain: "Common Criteria / Change Management",
        description: "System and application changes are documented, tested in staging, and approved prior to production release.",
        mappedFrameworks: ["ISO 27001", "SOC 1"],
      },
      {
        id: "A1.2",
        title: "System Availability, Redundancy, and Capacity Management",
        domain: "Availability Criteria",
        description: "Environmental redundancy, automated failover, and capacity forecasts ensure continuous availability meeting SLA targets.",
        mappedFrameworks: ["ISO 27001", "DORA"],
      },
      {
        id: "C1.1",
        title: "Confidentiality Identification and Cryptographic Erasure",
        domain: "Confidentiality Criteria",
        description: "Confidential customer data is identified, classified, and protected against unauthorized disclosure throughout its lifecycle.",
        mappedFrameworks: ["ISO 27001", "GDPR"],
      },
    ],
  },
  {
    id: "iso-27001",
    name: "ISO/IEC 27001:2022 - Information Security Management",
    shortName: "ISO 27001",
    version: "2022",
    category: "Information Security",
    description: "International standard specifying the requirements for establishing, implementing, maintaining and continually improving an Information Security Management System (ISMS).",
    controls: [
      {
        id: "A.5.1",
        title: "Policies for information security",
        domain: "Organizational Controls",
        description: "Information security policy and topic-specific policies shall be defined, approved by management, published, communicated to and acknowledged by relevant personnel.",
        mappedFrameworks: ["NIST CSF", "SOC 2"],
      },
      {
        id: "A.5.15",
        title: "Access control",
        domain: "Organizational Controls",
        description: "Rules to control physical and logical access to information and other associated assets shall be established and documented based on business requirements.",
        mappedFrameworks: ["SOC 2", "NIST CSF"],
      },
      {
        id: "A.5.23",
        title: "Information security for use of cloud services",
        domain: "Organizational Controls",
        description: "Processes for acquisition, use, management and exit from cloud services shall be established in accordance with the organization’s information security requirements.",
        mappedFrameworks: ["SOC 2", "CSA CCM"],
      },
      {
        id: "A.8.2",
        title: "Privileged access rights",
        domain: "Technological Controls",
        description: "The allocation and use of privileged access rights shall be restricted and managed.",
        mappedFrameworks: ["SOC 2", "NIST CSF", "PCI DSS"],
      },
      {
        id: "A.8.5",
        title: "Secure authentication",
        domain: "Technological Controls",
        description: "Secure authentication technologies and procedures shall be implemented based on information access restrictions and system access policy.",
        mappedFrameworks: ["SOC 2", "NIST CSF", "PCI DSS"],
      },
      {
        id: "A.8.15",
        title: "Logging and monitoring",
        domain: "Technological Controls",
        description: "Logs that record activities, exceptions, faults and other relevant events shall be produced, stored, protected and analyzed.",
        mappedFrameworks: ["SOC 2", "NIST CSF"],
      },
      {
        id: "A.8.24",
        title: "Use of cryptography",
        domain: "Technological Controls",
        description: "Rules for the effective use of cryptography, including cryptographic key management, shall be defined and implemented.",
        mappedFrameworks: ["SOC 2", "PCI DSS"],
      },
    ],
  },
  {
    id: "nist-csf",
    name: "NIST Cybersecurity Framework 2.0 (CSF 2.0)",
    shortName: "NIST CSF",
    version: "2.0",
    category: "Cybersecurity",
    description: "Guidance based on existing standards, guidelines, and practices for organizations to better manage and reduce cybersecurity risk across six core functions.",
    controls: [
      {
        id: "GV.OC-01",
        title: "Organizational Context",
        domain: "Govern",
        description: "The organizational mission, objectives, stakeholders, and legal/regulatory requirements are understood and inform cybersecurity risk management.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "ID.AM-01",
        title: "Inventories of Hardware & Systems",
        domain: "Identify",
        description: "Inventories of hardware, software, services, and external information systems are maintained.",
        mappedFrameworks: ["ISO 27001", "CIS Controls"],
      },
      {
        id: "PR.AA-01",
        title: "Identities and credentials",
        domain: "Protect",
        description: "Identities and credentials for authorized users, services, and hardware are managed.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "PR.DS-01",
        title: "Data protection at rest",
        domain: "Protect",
        description: "Data at rest is protected according to the organization’s risk strategy using verified encryption.",
        mappedFrameworks: ["ISO 27001", "PCI DSS"],
      },
      {
        id: "DE.CM-01",
        title: "Continuous network & asset monitoring",
        domain: "Detect",
        description: "Networks and operational environments are monitored to detect potential cybersecurity events.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "RS.MA-01",
        title: "Incident response management",
        domain: "Respond",
        description: "Incident response plans are executed in response to declared cybersecurity incidents.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "RC.RP-01",
        title: "Recovery plan execution",
        domain: "Recover",
        description: "Recovery processes and procedures are executed and maintained to restore impaired systems and services.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
    ],
  },
  {
    id: "nist-rmf",
    name: "NIST Risk Management Framework (RMF Rev. 5)",
    shortName: "NIST RMF",
    version: "Rev. 5",
    category: "Risk Management",
    description: "Seven-step structured process for managing organizational risk arising from operation and use of information systems per NIST SP 800-37.",
    controls: [
      {
        id: "RMF-1",
        title: "Prepare - Institutional risk management preparation",
        domain: "Prepare",
        description: "Organizational and system-level activities prepare the entity to manage security and privacy risks using the RMF.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
      {
        id: "RMF-2",
        title: "Categorize - Information system impact categorization",
        domain: "Categorize",
        description: "Categorize the system and the information processed, stored, and transmitted based on an impact analysis.",
        mappedFrameworks: ["ISO 27001"],
      },
      {
        id: "RMF-3",
        title: "Select - Security and privacy control baseline selection",
        domain: "Select",
        description: "Select an initial set of baseline security and privacy controls for the system and tailor them as appropriate.",
        mappedFrameworks: ["ISO 27001", "NIST 800-53"],
      },
      {
        id: "RMF-4",
        title: "Implement - Technical access enforcement & deployment",
        domain: "Implement",
        description: "Implement the security and privacy controls and document how the controls are deployed within the system.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "RMF-5",
        title: "Assess - Control effectiveness verification",
        domain: "Assess",
        description: "Assess the controls to determine if they are implemented correctly, operating as intended, and producing desired outcomes.",
        mappedFrameworks: ["ISO 27001", "SOC 2"],
      },
      {
        id: "RMF-6",
        title: "Authorize - Authorizing official risk determination",
        domain: "Authorize",
        description: "Authorize system operation based on a determination of the risk to organizational operations and assets.",
        mappedFrameworks: ["ISO 27001"],
      },
      {
        id: "RMF-7",
        title: "Monitor - Ongoing security and privacy monitoring",
        domain: "Monitor",
        description: "Continuously monitor control implementation and system security/privacy posture.",
        mappedFrameworks: ["ISO 27001", "NIST CSF"],
      },
    ],
  },
];
